# Generated by Django 3.2.10 on 2023-08-08 10:19

import SentMailManagement.models
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMailType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('organization', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tổ chức', null=True)),
                ('hr_created_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người tạo', null=True)),
                ('hr_updated_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người cập nhật', null=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('is_default', models.BooleanField(blank=True, default=True, help_text='Mặc định', null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtype_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtype_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Loại email',
                'verbose_name_plural': 'Loại email',
            },
        ),
        migrations.CreateModel(
            name='SystemMailTemplateImportStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('icon_class', models.CharField(help_text='Class icon', max_length=100, null=True)),
                ('color_class', models.CharField(help_text='Class màu', max_length=100, null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtemplateimportstatus_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtemplateimportstatus_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Trạng thái tải lên Mẫu email',
                'verbose_name_plural': 'Trạng thái tải lên Mẫu email',
            },
        ),
        migrations.CreateModel(
            name='SystemMailTemplateImportData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('file', models.FileField(help_text='Tệp dữ liệu', null=True, upload_to=SentMailManagement.models._upload_to)),
                ('total_record_number', models.IntegerField(help_text='Số lượng dữ liệu tải lên', null=True)),
                ('is_import_failed', models.BooleanField(default=False, help_text='Tải lên lỗi', null=True)),
                ('is_import_success', models.BooleanField(default=True, help_text='Tải thành công', null=True)),
                ('json_import_data', models.TextField(help_text='dữ liệu tải lên(json)', max_length=50000, null=True)),
                ('json_check_validation', models.TextField(help_text='dữ liệu không thỏa mãn yêu cầu', max_length=50000, null=True)),
                ('json_fail_data', models.TextField(help_text='dữ liệu bị lỗi', max_length=50000, null=True)),
                ('import_status', django.contrib.postgres.fields.hstore.HStoreField(help_text='Trạng thái tải lên', null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtemplateimportdata_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtemplateimportdata_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Tải lên Mẫu email',
                'verbose_name_plural': 'Tải lên Mẫu email',
            },
        ),
        migrations.CreateModel(
            name='SystemMailTemplate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('email_type', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Loại email', null=True)),
                ('content', models.TextField(blank=True, help_text='Nội dung', max_length=50000, null=True)),
                ('is_default', models.BooleanField(blank=True, help_text='Mặc định', null=True)),
                ('organization', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tổ chức', null=True)),
                ('hr_created_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người tạo', null=True)),
                ('hr_updated_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người cập nhật', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtemplate_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtemplate_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Mẫu email',
                'verbose_name_plural': 'Mẫu email',
            },
        ),
        migrations.CreateModel(
            name='SystemMailTarget',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('email_template', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Mẫu email', null=True)),
                ('target', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text='Người nhận mail', null=True, size=None)),
                ('content', models.TextField(blank=True, help_text='Nội dung', max_length=50000, null=True)),
                ('status_code', models.CharField(blank=True, help_text='Mã trạng thái', max_length=500, null=True)),
                ('status_text', models.CharField(blank=True, help_text='Trạng thái', max_length=500, null=True)),
                ('organization', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tổ chức', null=True)),
                ('hr_created_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người tạo', null=True)),
                ('hr_updated_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người cập nhật', null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtarget_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailtarget_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Cá nhân/nhóm nhận mail',
                'verbose_name_plural': 'Cá nhân/nhóm nhận mail',
            },
        ),
        migrations.CreateModel(
            name='SystemMailServerConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('host', models.CharField(blank=True, help_text='Host', max_length=500, null=True)),
                ('port', models.CharField(blank=True, help_text='Port', max_length=500, null=True)),
                ('port_smtp', models.CharField(blank=True, help_text='Port SMTP', max_length=500, null=True)),
                ('is_ssl', models.BooleanField(blank=True, help_text='SSL', null=True)),
                ('limit_sending', models.IntegerField(blank=True, help_text='Giới hạn gửi', null=True)),
                ('is_default', models.BooleanField(blank=True, default=True, help_text='Mặc định', null=True)),
                ('hr_created_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người tạo', null=True)),
                ('hr_updated_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người cập nhật', null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('organization', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tổ chức', null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailserverconfig_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailserverconfig_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Cấu hình email server',
                'verbose_name_plural': 'Cấu hình email server',
            },
        ),
        migrations.CreateModel(
            name='SystemMailSentMail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('organization', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tổ chức', null=True)),
                ('addressee', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người nhận', null=True)),
                ('mail', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Mail cần gửi đi', null=True)),
                ('mail_sender', models.CharField(blank=True, help_text='Tên mail gửi', max_length=500, null=True)),
                ('to_email', models.CharField(blank=True, help_text='Tên mail nhận', max_length=500, null=True)),
                ('status_code', models.CharField(blank=True, help_text='Mã trạng thái', max_length=500, null=True)),
                ('status_text', models.CharField(blank=True, help_text='Trạng thái', max_length=500, null=True)),
                ('hr_created_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người tạo', null=True)),
                ('hr_updated_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người cập nhật', null=True)),
                ('content', models.TextField(blank=True, help_text='Nội dung', max_length=50000, null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailsentmail_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailsentmail_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Mail đã gửi',
                'verbose_name_plural': 'Mail đã gửi',
            },
        ),
        migrations.CreateModel(
            name='SystemMailSenderConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('organization', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tổ chức', null=True)),
                ('email_server', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Email server', null=True)),
                ('email', models.CharField(blank=True, help_text='Email', max_length=500, null=True)),
                ('password', models.CharField(blank=True, help_text='Mật khẩu', max_length=500, null=True)),
                ('app_password', models.CharField(blank=True, help_text='Mật khẩu app', max_length=500, null=True)),
                ('hr_created_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người tạo', null=True)),
                ('hr_updated_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người cập nhật', null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailsenderconfig_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailsenderconfig_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Cấu hình email gửi đi',
                'verbose_name_plural': 'Cấu hình email gửi đi',
            },
        ),
        migrations.CreateModel(
            name='SystemMailMail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Tên', max_length=2000)),
                ('code', models.CharField(default='', editable=False, help_text='Mã', max_length=100)),
                ('friendly_code', models.CharField(help_text='Mã', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('organization', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tổ chức', null=True)),
                ('mail_sender', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Email gửi đi', null=True)),
                ('email_template', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Mẫu email', null=True)),
                ('mail_target', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Cá nhân/nhóm nhận mail', null=True)),
                ('addressee', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người nhận', null=True)),
                ('content', models.TextField(blank=True, help_text='Nội dung', max_length=50000, null=True)),
                ('status_code', models.CharField(blank=True, help_text='Mã trạng thái', max_length=500, null=True)),
                ('status_text', models.CharField(blank=True, help_text='Trạng thái', max_length=500, null=True)),
                ('hr_created_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người tạo', null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('hr_updated_by', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Người cập nhật', null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailmail_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentmailmanagement_systemmailmail_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Mail cần gửi',
                'verbose_name_plural': 'Mail cần gửi',
            },
        ),
    ]
