# Generated by Django 3.2.10 on 2023-08-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentMailManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmailserverconfig',
            name='active',
            field=models.BooleanField(blank=True, default=True, help_text='Hoạt động', null=True),
        ),
    ]
