# Generated by Django 3.2.10 on 2024-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentMailManagement', '0005_systemmailmail_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmailtemplate',
            name='subject_of_template',
            field=models.CharField(default='', help_text='Tiêu đề của mẫu mail', max_length=2000),
        ),
    ]
